name: flutter_qiblah_latest_example
description: "Demonstrates how to use the flutter_qiblah_latest plugin."
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_qiblah_latest:
    path: ../

  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.5.3

  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
